#!/usr/bin/env python3
import os

os.environ['DELCH_ADDRESS'] = 'http://127.0.0.1:5000'

if 'DELCH_ADDRESS' in os.environ:
    print('DELCH_ADDRESS environment variable defined. Value =', os.environ['DELCH_ADDRESS'])
else:
    print('FAILLED to define environment variable')