#!/usr/bin/env python3
import sys
import requests

funct=sys.argv[1]

if funct=="add":
    requests.post('http://127.0.0.1:5000/Tarefa/', data={'data':sys.argv[2]})
elif funct=="list":
    r=requests.get('http://127.0.0.1:5000/Tarefa/')
    print (r.text)
elif funct=="search":
    r=requests.get('http://127.0.0.1:5000/Tarefa/{}'.format(sys.argv[2]))
    print (r.text)
elif funct=="delete":
    requests.delete('http://127.0.0.1:5000/Tarefa/{}'.format(sys.argv[2]))
elif funct=="update":
    requests.put('http://127.0.0.1:5000/Tarefa/{}'.format(sys.argv[2]), data={'data':sys.argv[3]})
else:
    print('Funct not valid ')
                    